{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "velero-pvc-watcher.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "velero-pvc-watcher.name" . }}
{{ include "velero-pvc-watcher.labels" . | indent 4 }}
spec:
  endpoints:
  - port: http
    path: {{ .Values.metrics.serviceMonitor.path }}
    {{- if .Values.metrics.serviceMonitor.interval }}
    interval: {{ .Values.metrics.serviceMonitor.interval }}
    {{- end }}
{{- if .Values.metrics.serviceMonitor.metricRelabelings }}
    metricRelabelings:
{{ tpl (toYaml .Values.metrics.serviceMonitor.metricRelabelings | indent 6) . }}
{{- end }}
{{- if .Values.metrics.serviceMonitor.relabelings }}
    relabelings:
{{ toYaml .Values.metrics.serviceMonitor.relabelings | indent 6 }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "velero-pvc-watcher.name" . }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
{{- end }}
